# Generated by Django 2.1.3 on 2018-11-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
