# Generated by Django 2.1.3 on 2018-11-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='photos', verbose_name='profile picture'),
        ),
    ]
